// <auto-generated />
namespace MV2ReportsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Rep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rep));
        
        string IMigrationMetadata.Id
        {
            get { return "201811221443287_Rep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
